<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simu.Core\Simu.Core.csproj" />
    <ProjectReference Include="..\Simu.Data\Simu.Data.csproj" />
    <ProjectReference Include="..\Simu.Business\Simu.Business.csproj" />
  </ItemGroup>

</Project>
